name: check PR
on: 
  pull_request:
    types: [synchronize, opened, reopened, edited]
jobs:
  check-pr:
    runs-on: hashicorp/terraform:1.0.7
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: List files
        run: |
          pwd
          ls -la
          grep . * || :
      - name: Validate Terraform configuration
        run: |
          for module in $(find . -name '*.tf' -exec dirname {} \; | sort -u); do (
            cd "$module" || exit 1
            echo -n "Validating $module"
            terraform init || exit 1
            terraform validate || exit 1
          ); done
