name: check PR
on: 
  - pull_request
jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: List files
        run: |
          pwd
          ls -la
          grep . * || :
      - name: Validate Terraform configuration
        uses: devops-infra/action-terraform-validate@v0.3
