name: check PR
on: 
  - pull_request
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: List files
        run: grep . -r
